### ISSUE TITLE
'com.google.android.gms' conflict with phonegap-plugin-push

### ISSUE THREAD

**Issue by GavinHellyer** [appfeel/analytics-google-adid#5]
I am getting a conflict with com.google.android.gms when using this plugin with phonegap-plugin-push.

```
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
```

Any assistance here as I need to use Push Notifications as well as use the ADID data.

**Comment by enricodeleo** [comment]
+1 
the same happens to me. It is limited to Android apparently because of cordova-google-play-services plugin being installed automatically.

**Comment by Ziv-Barber** [comment]
See issue #7 for my work around.
Use it any time that you have a problem like that.

**Comment by miqmago** [comment]
Fixed in the new version of the plugin

**Comment by degaray** [comment]
I am still getting it. I recently upgraded my SDK and Cordova and it is now giving the same error
